name: Azure Function Deploy With CICD.
on:
  workflow_dispatch:
jobs: 
  deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
          architecture: x64

      - name: Install required python modules AzureFunctionDeploy
        run: |
          cd ./AzureFunctionDeploy
          python -m pip install --upgrade pip
          pip install --target="./.python_packages/lib/site-packages" -r requirements.txt 

      - name: Zip the Azure Python Function Deploy folder
        run: |
          cd AzureFunctionDeploy
          zip -r ../AzureFunctionDeploy.zip ./*

      # - name: Install required python modules AzureStorageQueueTriggerFunction 
      #   run: |
      #     cd ./AzureStorageQueueTriggerFunction
      #     python -m pip install --upgrade pip
      #     pip install --target="./.python_packages/lib/site-packages" -r requirements.txt 

      # - name: Zip the Azure Function Deploy folder AzureStorageQueueTriggerFunction
      #   run: |
      #     cd AzureStorageQueueTriggerFunction
      #     zip -r ../AzureStorageQueueTriggerFunction.zip ./*


    # These secrets should be added to your GitHub repository's secrets settings.
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }
      
  
      - name: 'Run az commands'
        run: |
          az account show
    
      - name: Build and Deploy to Azure Python Function
        run: |
          az functionapp deployment source config-zip \
            --resource-group "demofunctionapp-rg" \
            --name "pythonfunctionappjp" \
            --src "./AzureFunctionDeploy.zip"

      # - name: Build and Deploy to Azure Queue Function
      #   run: |
      #     az functionapp deployment source config-zip \
      #       --resource-group "demofunctionapp-rg" \
      #       --name "pythonfunctionappjp" \
      #       --src "./AzureStorageQueueTriggerFunction.zip"
